### ISSUE TITLE
Assert when loading titlegame with AI

### ISSUE THREAD

**Issue by 2TallTyler** [OpenTTD/OpenTTD#10206]
### Version of OpenTTD

13.0-beta2

### Expected result

According to our longtime Title Game Competition rules, AI, GS, and NewGRFs used in a title game are automatically disabled.

I would expect if an AI is present, the AI company is deleted or the game loads the all-water fallback instead, like when a NewGRF is present.

### Actual result

If an AI is used, we get an assertion failure:
`Assertion failed at line 94 of src\ai\ai_config.cpp: strcmp("start_date", name) == 0`

Logs and emergency save:
[crash20221201165815.zip](https://github.com/OpenTTD/OpenTTD/files/10134454/crash20221201165815.zip)

### Steps to reproduce

1. Download the attached savegame and `opntitle.dat` of the same savegame
2. Place `opntitle.dat` in your baseset folder, replacing the file that's already there
3. Start OpenTTD

[title.zip](https://github.com/OpenTTD/OpenTTD/files/10134482/title.zip)

**Comment by PeterN** [comment]
Resolved: "Don't create a title game with AI/GS/NewGRFs"

;-)

**Comment by 2TallTyler** [comment]
Agreed, and the rules do say not to do it, I just wish it failed a bit nicer.

**Comment by glx22** [comment]
I think it's partly a duplicate of #9720, but with #9745 it still crashes in a different place.

**Comment by glx22** [comment]
Ok after some digging it might not be a direct duplicate, but it has the same causes.
Settings are correctly loaded as `_settings_game`, and the AI started, but as we are in `GM_MENU` `_settings_newgame` ones are used (expected).
So the crash is because the AI is started.
With #9745, the AI is not started, but `c->is_ai` being true the game assumes it has started (dereferencing nullptr at some point).
So I need to update #9745 to set `c->is_ai` to false when loading intro, and also discard ScriptData in this case as no start means the used memory is not released (and I noticed the not releasing part also happens for network games on client side).
