### ISSUE TITLE
Ship automatic service causes them to be stuck in a loop

### ISSUE THREAD

**Issue by SamuXarick** [OpenTTD/OpenTTD#8022]
## Version of OpenTTD
~~OpenTTD 20200223-master-gd1b7eb2de1~~ - Resolved by #11768
OpenTTD 20240128-master-g90084dc74d
## Expected result
Ships either do service or not.
## Actual result
Ships are stuck in a loop due to automatic servicing distance limit triggering it. They can't decide whether to head to ship depot or the dock, which are opposite directions.
## Steps to reproduce
~~[Charningstone Transport, 1960-11-25.zip](https://github.com/OpenTTD/OpenTTD/files/4250827/Charningstone.Transport.1960-11-25.zip)~~ - Resolved by #11768

[Charningstone Transport, 1964-05-30.zip](https://github.com/OpenTTD/OpenTTD/files/14077702/Charningstone.Transport.1964-05-30.zip) - Not resolved

**Comment by SamuXarick** [comment]
I have a fix for this which envolves using the pathfinder, but the idea has been rejected in the past, which was before ship path cache. Is it perhaps worth approaching it again?
https://github.com/SamuXarick/OpenTTD/tree/find-closest-reachable-ship-depot

**Comment by SamuXarick** [comment]
For this specific savegame, it is fixed by #11768, but I'm not sure this is solved in other situations.

**Comment by hpiirai** [comment]
Just a reminder that this bug is still present in **20251213-master-g1091fa6071**.

Try [Gribble & Co., 1877-06-21.sav.gz](https://github.com/user-attachments/files/24140752/Gribble.Co.1877-06-21.sav.gz) if you dare.
